import { expect, test } from '@playwright/test'
import { enterCinemaLibrary, installCinema as install } from './cinema-helpers'

test('影视库内首页、详情、收藏和字幕续播，不在点击播放前读取原视频', async ({ page }, info) => {
  const errors: string[] = [], outside: string[] = [], previewReads: number[] = []
  page.on('pageerror', e => errors.push(e.message))
  // 从打开影院前开始计数，不能漏掉首页首屏可能发出的原视频请求。
  page.on('request', request => {
    if (/^https?:/.test(request.url()) && !request.url().startsWith('http://127.0.0.1:4187')) outside.push(request.url())
    const match = /\/api\/apps\/media\/([^/?]+)/.exec(request.url())
    if (!match) return
    const claim = JSON.parse(Buffer.from(match[1]!.split('.')[0]!, 'base64url').toString())
    if (claim.purpose === 'preview') previewReads.push(claim.node_id)
  })
  await install(page)
  const frame = page.frameLocator('iframe')
  const videoIds: number[] = await frame.locator('body').evaluate(async () => {
    const drive = (window as any).tgdrive
    return (await drive.files.searchPage({ under: '/测试影视', extensions: ['mp4', 'mkv', 'avi', 'webm'] })).results.map((file: any) => file.id)
  })
  await frame.getByRole('button', { name: '查看影视：星际旅程 S01E01.mp4', exact: true }).click()
  await expect(frame.locator('#episode-count')).toContainText('3 个视频')
  expect(previewReads.filter(id => videoIds.includes(id))).toHaveLength(0)
  await frame.locator('#detail-favorite').click()
  await expect(frame.locator('#detail-favorite')).toHaveAttribute('aria-pressed', 'true')
  await page.screenshot({ path: info.outputPath('cinema-desktop-detail.png'), fullPage: true })
  await frame.locator('#detail-play').click()
  await expect.poll(() => frame.locator('#video').evaluate(v => (v as HTMLVideoElement).currentTime), { timeout: 25000 }).toBeGreaterThan(1)
  await frame.locator('#options-toggle').click()
  await expect(frame.locator('#subtitle option')).toHaveCount(2)
  await expect.poll(() => frame.locator('#video').evaluate(v => (v as HTMLVideoElement).textTracks[0]?.cues?.length ?? 0)).toBe(2)
  await frame.locator('#subtitle').selectOption('')
  await frame.locator('#options-close').click()
  await frame.locator('#forward').click()
  await expect.poll(() => frame.locator('#video').evaluate(v => (v as HTMLVideoElement).currentTime)).toBeGreaterThan(10)
  await frame.locator('#player-back').click()
  await expect(frame.locator('#continue-section')).toBeVisible()
  await page.reload()
  await enterCinemaLibrary(page)
  await frame.getByRole('button', { name: '继续观看：星际旅程 S01E01.mp4', exact: true }).click()
  await expect.poll(() => frame.locator('#video').evaluate(v => (v as HTMLVideoElement).currentTime)).toBeGreaterThan(10)
  await frame.locator('#options-toggle').click()
  await expect(frame.locator('#subtitle')).toHaveValue('')
  await frame.locator('#player-back').click()
  await frame.locator('.sidebar [data-nav="favorites"]').click()
  await expect(frame.locator('#items .poster-card')).toHaveCount(1)
  expect(errors).toEqual([]); expect(outside).toEqual([])
})

test('真实 MKV 经客户端转封装播放、音轨切换、内嵌字幕和拖动', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await install(page)
  const frame = page.frameLocator('iframe')
  await frame.getByRole('button', { name: '查看影视：星际旅程 S01E02.mkv', exact: true }).click()
  await frame.locator('#detail-play').click()
  await expect(frame.locator('#play-mode')).toContainText('客户端转封装', { timeout: 25000 })
  await expect.poll(() => frame.locator('#video').evaluate(v => (v as HTMLVideoElement).currentTime), { timeout: 30000 }).toBeGreaterThan(1)
  await expect(frame.locator('#video')).toHaveAttribute('src', /^blob:/)
  await frame.locator('#options-toggle').click()
  await expect(frame.locator('#audio option')).toHaveCount(2)
  await frame.locator('#subtitle').selectOption('embedded:4')
  await expect.poll(() => frame.locator('#video').evaluate(v => (v as HTMLVideoElement).textTracks[0]?.cues?.length ?? 0)).toBeGreaterThan(0)
  await frame.locator('#audio').selectOption({ index: 1 })
  await frame.locator('#options-close').click()
  await expect.poll(() => frame.locator('#video').evaluate(v => (v as HTMLVideoElement).currentTime), { timeout: 30000 }).toBeGreaterThan(2)
  await frame.locator('#forward').click()
  await expect.poll(() => frame.locator('#video').evaluate(v => (v as HTMLVideoElement).currentTime), { timeout: 30000 }).toBeGreaterThan(11)
  await frame.locator('#rewind').click()
  await expect.poll(() => frame.locator('#video').evaluate(v => (v as HTMLVideoElement).currentTime), { timeout: 30000 }).toBeLessThan(8)
  await frame.locator('#player-back').click()
  await expect(frame.locator('#video')).not.toHaveAttribute('src', /.+/)
  expect(errors).toEqual([])
})

test('手机影院布局、横屏、格式错误及无 MSE 降级', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await install(page)
  const frame = page.frameLocator('iframe')
  await expect(frame.locator('.bottom-nav')).toBeVisible()
  expect(await frame.locator('body').evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('cinema-mobile.png'), fullPage: true })
  await frame.getByRole('button', { name: '查看影视：错误示例.avi', exact: true }).click()
  await frame.locator('#detail-play').click()
  await expect(frame.locator('#play-message')).toContainText('不支持', { timeout: 15000 })
  await frame.locator('#player-back').click()
  await frame.locator('body').evaluate(() => { Object.defineProperty(window, 'MediaSource', { value: undefined, configurable: true }) })
  await frame.getByRole('button', { name: '查看影视：星际旅程 S01E02.mkv', exact: true }).click()
  await frame.locator('#detail-play').click()
  await expect(frame.locator('#play-message')).toContainText('缺少 MediaSource')
  await page.setViewportSize({ width: 844, height: 390 })
  await expect(frame.locator('#player-back')).toBeVisible()
  await frame.locator('#player-back').click()
  expect(await frame.locator('body').evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
})

test('WebM 的 VP9 与 Opus 使用原生播放，不强制转封装', async ({ page }) => {
  await install(page, '/测试影视/原生示例')
  const frame = page.frameLocator('iframe')
  await frame.getByRole('button', { name: '查看影视：流光.webm', exact: true }).click()
  await frame.locator('#detail-play').click()
  await expect.poll(() => frame.locator('#video').evaluate(v => (v as HTMLVideoElement).currentTime)).toBeGreaterThan(.2)
  await expect(frame.locator('#play-mode')).toHaveText('原生播放')
  await expect(frame.locator('#video')).toHaveAttribute('src', /\/api\/apps\/media\//)
  await frame.locator('#player-back').click()
  await expect(frame.locator('#video')).not.toHaveAttribute('src', /.+/)
})

test('暂停后的 MKV 拖动及切换音轨保持暂停，并保存位置和音轨', async ({ page }) => {
  await install(page)
  const frame = page.frameLocator('iframe')
  await frame.getByRole('button', { name: '查看影视：星际旅程 S01E02.mkv', exact: true }).click()
  await frame.locator('#detail-play').click()
  const playback = () => frame.locator('#video').evaluate(v => ({ time: (v as HTMLVideoElement).currentTime, paused: (v as HTMLVideoElement).paused, seeking: (v as HTMLVideoElement).seeking }))
  await expect.poll(async () => (await playback()).time).toBeGreaterThan(1)
  await frame.locator('#toggle-play').click()
  await expect.poll(async () => (await playback()).paused).toBe(true)
  await frame.locator('#forward').click()
  await expect.poll(async () => (await playback()).time).toBeGreaterThan(10)
  await expect.poll(async () => (await playback()).seeking).toBe(false)
  expect((await playback()).paused).toBe(true)
  await frame.locator('#options-toggle').click()
  await frame.locator('#audio').selectOption({ index: 1 })
  await expect.poll(async () => (await playback()).time).toBeGreaterThan(10)
  await expect.poll(async () => (await playback()).seeking).toBe(false)
  expect((await playback()).paused).toBe(true)
  const audio = await frame.locator('#audio').inputValue()
  await frame.locator('#player-back').click()
  await frame.getByRole('button', { name: '继续观看：星际旅程 S01E02.mkv', exact: true }).click()
  await expect.poll(async () => (await playback()).time).toBeGreaterThan(10)
  await frame.locator('#options-toggle').click()
  await expect(frame.locator('#audio')).toHaveValue(audio)
})

test('详情未整理完就播放，仍能恢复同目录选集和下一集', async ({ page }) => {
  await install(page)
  const frame = page.frameLocator('iframe')
  let release!: () => void
  const gate = new Promise<void>(resolve => { release = resolve })
  let intercepted = false
  await page.route('**/api/apps/cinema/rpc', async route => {
    const body = route.request().postDataJSON()
    if (!intercepted && body.method === 'storage.get' && body.params.key.startsWith('favorite:')) {
      intercepted = true
      await gate
    }
    await route.continue().catch(() => {})
  })
  try {
    await frame.getByRole('button', { name: '查看影视：星际旅程 S01E01.mp4', exact: true }).click()
    await expect.poll(() => intercepted).toBe(true)
    await expect(frame.locator('#detail-status')).toHaveText('正在整理同目录合集…')
    await frame.locator('#detail-play').click()
    await expect.poll(() => frame.locator('#video').evaluate(v => (v as HTMLVideoElement).currentTime)).toBeGreaterThan(.2)
    await expect(frame.locator('#next-episode')).toBeEnabled()
    await frame.locator('#next-episode').click()
    await expect(frame.locator('#playing-title')).toContainText('S01E02')
    await expect(frame.locator('#play-mode')).toContainText('客户端转封装')
  } finally { release() }
})

test('播放器键盘焦点不落到背后的片库，退出后恢复导航', async ({ page }) => {
  await install(page, '/测试影视/原生示例')
  const frame = page.frameLocator('iframe')
  await frame.getByRole('button', { name: '查看影视：流光.webm', exact: true }).click()
  await frame.locator('#detail-play').click()
  await expect.poll(() => frame.locator('#video').evaluate(v => (v as HTMLVideoElement).currentTime)).toBeGreaterThan(.2)
  await expect(frame.getByRole('dialog', { name: '影视播放器' })).toBeVisible()
  expect(await frame.locator('#main').evaluate(node => (node as HTMLElement).inert)).toBe(true)
  await frame.locator('#player-back').focus()
  await page.keyboard.press('Shift+Tab')
  await expect(frame.locator('#fullscreen')).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(frame.locator('#player-back')).toBeFocused()
  await frame.locator('#options-toggle').click()
  await page.keyboard.press('Escape')
  await expect(frame.locator('#play-options')).not.toBeVisible()
  await expect(frame.locator('#options-toggle')).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(frame.locator('#player')).not.toBeVisible()
  expect(await frame.locator('#main').evaluate(node => (node as HTMLElement).inert)).toBe(false)
  await expect(frame.locator('#main')).toBeFocused()
})
