import { expect, test, type Page } from '@playwright/test'
import { legacyCinemaPackage } from './cinema-legacy-package'
import { chooseCinemaDirectory, cinemaRequests, createCinemaLibrary, enterCinemaLibrary, installCinema } from './cinema-helpers'

const frameOf = (page: Page) => page.frameLocator('iframe')
const readConfig = (page: Page) => frameOf(page).locator('body').evaluate(async () => (await (window as any).tgdrive.storage.get('media-libraries'))?.value)
async function rename(page: Page, from: string, to: string) {
  expect((await page.request.post('/api/fs/rename', { data: { from, to } })).ok()).toBe(true)
}
test('先创建命名媒体库，进入后仅查询所选范围，重新打开不会自动加载', async ({ page }) => {
  const audit = cinemaRequests(page)
  await installCinema(page, null)
  const frame = frameOf(page)
  expect(audit.enumerations()).toEqual([])
  expect(audit.calls.filter(call => call.method === 'media.url')).toEqual([])
  await createCinemaLibrary(page, '电影', '/测试影视')
  await createCinemaLibrary(page, '电视剧', '/测试视频')
  expect(audit.enumerations()).toEqual([])
  expect(await readConfig(page)).toMatchObject({ schemaVersion: 1, libraries: [{ name: '电影', directoryPath: '/测试影视' }, { name: '电视剧', directoryPath: '/测试视频' }] })

  await enterCinemaLibrary(page, '电影')
  await expect(frame.getByRole('button', { name: '查看影视：流光.webm', exact: true })).toBeVisible()
  await expect(frame.getByRole('button', { name: '查看影视：片段 A.webm', exact: true })).toHaveCount(0)
  await frame.locator('#search').fill('星际旅程')
  await frame.locator('#search-form').getByRole('button', { name: '搜索', exact: true }).click()
  await expect(frame.locator('#items .poster-card')).toHaveCount(2)
  await frame.locator('#format').selectOption('mkv')
  await expect(frame.locator('#items .poster-card')).toHaveCount(1)
  await frame.locator('#format').selectOption('')
  await expect(frame.locator('#items .poster-card')).toHaveCount(2)
  await frame.locator('#search').fill('流光')
  await frame.locator('#search').press('Enter')
  await expect(frame.getByRole('button', { name: '查看影视：流光.webm', exact: true })).toBeVisible()
  await expect(frame.locator('#items .poster-card')).toHaveCount(1)
  await frame.locator('#directory-mode').click()
  await expect(frame.locator('#breadcrumbs button')).toBeDisabled()
  await frame.getByRole('button', { name: '打开目录：原生示例', exact: true }).click()
  await expect(frame.locator('#breadcrumbs')).toContainText('/测试影视/原生示例')
  await expect(frame.locator('#items .poster-card')).toHaveCount(1)
  await frame.locator('#breadcrumbs button').click()
  await expect(frame.locator('#breadcrumbs button')).toBeDisabled()
  expect(audit.enumerations().every(call => call.method === 'files.searchPage' ? call.params.under === '/测试影视' : call.params.path === '/测试影视' || call.params.path.startsWith('/测试影视/'))).toBe(true)

  audit.calls.length = 0
  await page.reload()
  await expect(frame.locator('#libraries .library-card')).toHaveCount(2)
  await expect(frame.locator('#items .poster-card')).toHaveCount(0)
  await expect(frame.locator('#hero')).not.toBeVisible()
  expect(audit.enumerations()).toEqual([])
  expect(audit.calls.filter(call => call.method === 'files.stat' || call.method === 'media.url')).toEqual([])
})

test('根目录需要额外确认，取消目录选择和取消确认均不改变配置', async ({ page }) => {
  const audit = cinemaRequests(page)
  await installCinema(page, null)
  const frame = frameOf(page)
  await frame.locator('#new-library').click()
  await expect(frame.locator('#library-name')).toBeEnabled()
  await frame.locator('#library-name').fill('全盘影视')
  await chooseCinemaDirectory(page, '/')
  await frame.locator('#library-save').click()
  await expect(frame.locator('#confirm-title')).toHaveText('将整个网盘加入媒体库？')
  await frame.locator('#confirm-cancel').click()
  await expect(frame.locator('#library-edit-dialog')).toBeVisible()
  expect(await readConfig(page)).toBeUndefined()
  await frame.locator('#library-pick').click()
  await page.getByRole('dialog', { name: '影视：选择目录', exact: true }).getByRole('button', { name: '取消', exact: true }).click()
  await expect(frame.locator('#library-path')).toHaveText('/')
  await expect(frame.locator('#library-name')).toHaveValue('全盘影视')
  await frame.locator('#library-save').click()
  await frame.locator('#confirm-ok').click()
  await expect(frame.getByRole('button', { name: '进入媒体库：全盘影视', exact: true })).toBeVisible()
  expect(audit.enumerations()).toEqual([])
  await enterCinemaLibrary(page, '全盘影视')
  expect(audit.enumerations().filter(call => call.method === 'files.searchPage').every(call => call.params.under === '/')).toBe(true)
})

test('收藏历史只显示当前范围，旧详情不能播放或下载移出的文件，记录保留并可恢复', async ({ page }) => {
  await installCinema(page, '/测试影视/原生示例', '电影')
  const frame = frameOf(page)
  const original = '/测试影视/原生示例/流光.webm', moved = '/空目录/流光.webm'
  const ids = await frame.locator('body').evaluate(async () => {
    const drive = (window as any).tgdrive
    const inside = await drive.files.stat({ path: '/测试影视/原生示例/流光.webm' })
    const outside = await drive.files.stat({ path: '/测试影视/星际旅程 S01E01.mp4' })
    for (const file of [inside, outside]) {
      await drive.storage.set(`favorite:${file.id}`, { file }, null)
      await drive.storage.set(`progress:${file.id}`, { file, seconds: 1, duration: 20, completed: false }, null)
    }
    return { inside: inside.id, outside: outside.id }
  })
  const audit = cinemaRequests(page)
  await frame.locator('.sidebar [data-nav="history"]').click()
  await expect(frame.locator('#items .poster-card')).toHaveCount(1)
  await expect(frame.getByRole('button', { name: '查看影视：流光.webm', exact: true })).toBeVisible()
  await frame.locator('.sidebar [data-nav="favorites"]').click()
  await expect(frame.locator('#items .poster-card')).toHaveCount(1)
  expect(audit.enumerations()).toEqual([])
  const thumbnails = () => audit.calls.filter(call => call.method === 'media.url' && call.params.kind === 'thumbnail' && call.params.id === ids.inside).length
  const before = thumbnails()
  await frame.getByRole('button', { name: '查看影视：流光.webm', exact: true }).click()
  await expect(frame.locator('#detail-favorite')).toBeEnabled()
  // 详情海报先查封面库再申请缩略图票据；等它在移出范围前完成，避免迟到的请求落进下面的审计窗口。
  await expect.poll(thumbnails).toBe(before + 1)
  await rename(page, original, moved)
  try {
    audit.calls.length = 0
    await frame.locator('#detail-download').click()
    await expect(frame.locator('#toast')).toContainText('范围内')
    await frame.locator('#detail-play').click()
    await expect(frame.locator('#play-message')).toContainText('范围内')
    await frame.locator('#player-download').click()
    await expect(frame.locator('#toast')).toContainText('范围内')
    expect(audit.calls.filter(call => call.method === 'media.url' && (call.params.id === ids.inside || call.params.path === moved))).toEqual([])
    await frame.locator('#player-back').click()
    await expect(frame.locator('#items .poster-card')).toHaveCount(0)
    const retained = await frame.locator('body').evaluate(async (_node, { inside, outside }) => {
      const drive = (window as any).tgdrive
      return Promise.all([inside, outside].flatMap(id => [drive.storage.get(`favorite:${id}`), drive.storage.get(`progress:${id}`)]))
    }, ids)
    expect(retained.every(Boolean)).toBe(true)
    await frame.locator('.sidebar [data-nav="library"]').click()
    await createCinemaLibrary(page, '临时片库', '/空目录')
    await frame.locator('.sidebar [data-nav="history"]').click()
    await expect(frame.locator('#items .poster-card')).toHaveCount(1)
    await expect(frame.getByRole('button', { name: '查看影视：流光.webm', exact: true })).toBeVisible()
    await frame.locator('.sidebar [data-nav="library"]').click()
    await frame.getByRole('button', { name: '删除媒体库：临时片库', exact: true }).click()
    await expect(frame.locator('#confirm-text')).toContainText('不删除原文件')
    await frame.locator('#confirm-ok').click()
    await expect(frame.getByRole('button', { name: '进入媒体库：临时片库', exact: true })).toHaveCount(0)
    await frame.locator('.sidebar [data-nav="history"]').click()
    await expect(frame.locator('#items .poster-card')).toHaveCount(0)
  } finally { await rename(page, moved, original) }
})

test('根目录按节点 ID 跟随移动，删除后不误绑定同路径新目录，可编辑重新绑定', async ({ page }) => {
  await installCinema(page, null)
  const frame = frameOf(page), oldPath = '/媒体库目录测试', newPath = '/媒体库目录测试改名'
  expect((await page.request.post('/api/fs/mkdir', { data: { path: oldPath } })).ok()).toBe(true)
  try {
    await createCinemaLibrary(page, '空片库', oldPath)
    const originalId = (await readConfig(page)).libraries[0].directoryId
    await rename(page, oldPath, newPath)
    expect((await page.request.post('/api/fs/mkdir', { data: { path: oldPath } })).ok()).toBe(true)
    await frame.getByRole('button', { name: '进入媒体库：空片库', exact: true }).click()
    await expect(frame.locator('#source-label')).toHaveText(newPath)
    await expect(frame.locator('#empty-title')).toHaveText('此媒体库还没有视频')
    const deleted = await page.request.post('/api/fs/delete', { data: { paths: [newPath], permanent: true } })
    expect((await deleted.json()).deleted).toBe(1)
    const audit = cinemaRequests(page)
    await frame.locator('#refresh').click()
    await expect(frame.locator('#list-status')).toContainText('文件夹不可用')
    expect(audit.enumerations()).toEqual([])
    await frame.locator('#library-edit-current').click()
    await expect(frame.locator('#library-name')).toBeEnabled()
    await frame.locator('#library-name').fill('重新绑定')
    await chooseCinemaDirectory(page, oldPath)
    await frame.locator('#library-save').click()
    await expect(frame.getByRole('button', { name: '进入媒体库：重新绑定', exact: true })).toBeVisible()
    expect((await readConfig(page)).libraries[0].directoryId).not.toBe(originalId)
    await frame.getByRole('button', { name: '删除媒体库：重新绑定', exact: true }).click()
    await frame.locator('#confirm-ok').click()
    await expect(frame.getByRole('button', { name: '进入媒体库：重新绑定', exact: true })).toHaveCount(0)
    await expect(frame.locator('#empty')).toBeVisible()
    expect((await (await page.request.get('/api/fs/list', { params: { path: oldPath } })).json()).path).toBe(oldPath)
    await expect.poll(async () => (await readConfig(page)).libraries).toEqual([])
  } finally {
    await page.request.post('/api/fs/delete', { data: { paths: [oldPath, newPath], permanent: true } })
  }
})

test('配置 CAS 冲突保留编辑草稿，重新确认不会丢失远端新增库，删除冲突也不覆盖', async ({ page }) => {
  await installCinema(page, null)
  const frame = frameOf(page)
  await createCinemaLibrary(page, '电影', '/测试影视')
  await frame.getByRole('button', { name: '编辑媒体库：电影', exact: true }).click()
  await expect(frame.locator('#library-name')).toBeEnabled()
  await frame.locator('#library-name').fill('珍藏电影')
  await frame.locator('body').evaluate(async () => {
    const drive = (window as any).tgdrive, record = await drive.storage.get('media-libraries')
    const directory = await drive.files.stat({ path: '/测试视频' })
    await drive.storage.set(record.key, { ...record.value, libraries: [...record.value.libraries, { id: 'remote-series', name: '电视剧', directoryId: directory.id, directoryPath: directory.path }] }, record.revision)
  })
  await frame.locator('#library-save').click()
  await expect(frame.locator('#library-edit-status')).toContainText('另一设备')
  await expect(frame.locator('#library-name')).toHaveValue('珍藏电影')
  expect((await readConfig(page)).libraries.map((item: any) => item.name)).toEqual(['电影', '电视剧'])
  await frame.locator('#library-name').press('Enter')
  await expect(frame.getByRole('button', { name: '进入媒体库：珍藏电影', exact: true })).toBeVisible()
  await expect(frame.getByRole('button', { name: '进入媒体库：电视剧', exact: true })).toBeVisible()
  await frame.getByRole('button', { name: '删除媒体库：电视剧', exact: true }).click()
  await expect(frame.locator('#confirm-dialog')).toBeVisible()
  await frame.locator('body').evaluate(async () => {
    const drive = (window as any).tgdrive, record = await drive.storage.get('media-libraries')
    record.value.libraries[1].name = '云端电视剧'
    await drive.storage.set(record.key, record.value, record.revision)
  })
  await frame.locator('#confirm-ok').click()
  await expect(frame.locator('#toast')).toContainText('本次没有删除')
  await expect(frame.getByRole('button', { name: '进入媒体库：云端电视剧', exact: true })).toBeVisible()
  expect((await readConfig(page)).libraries).toHaveLength(2)
})

test('切换媒体库取消旧查询，迟到响应不覆盖新库；配置读取失败不回退全盘', async ({ page }) => {
  await installCinema(page, null)
  const frame = frameOf(page)
  await createCinemaLibrary(page, '电影', '/测试影视')
  await createCinemaLibrary(page, '电视剧', '/测试视频')
  let release!: () => void, intercepted = false
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/apps/cinema/rpc', async route => {
    const body = route.request().postDataJSON()
    if (!intercepted && body.method === 'files.searchPage' && body.params.under === '/测试影视') {
      intercepted = true
      const response = await route.fetch()
      await gate
      await route.fulfill({ response }).catch(() => {})
    } else await route.continue()
  })
  try {
    await frame.getByRole('button', { name: '进入媒体库：电影', exact: true }).click()
    await expect.poll(() => intercepted).toBe(true)
    await frame.locator('.sidebar [data-nav="library"]').click()
    await enterCinemaLibrary(page, '电视剧')
    release()
    await expect(frame.locator('#page-title')).toHaveText('电视剧')
    await expect(frame.getByRole('button', { name: '查看影视：片段 A.webm', exact: true })).toBeVisible()
    await expect(frame.getByRole('button', { name: '查看影视：星际旅程 S01E01.mp4', exact: true })).toHaveCount(0)
  } finally { release(); await page.unroute('**/api/apps/cinema/rpc') }
  const audit = cinemaRequests(page)
  await page.route('**/api/apps/cinema/rpc', async route => {
    const body = route.request().postDataJSON()
    if (body.method === 'storage.get' && body.params.key === 'media-libraries') await route.fulfill({ status: 500, json: { error: '媒体库配置读取失败' } })
    else await route.continue()
  })
  await page.reload()
  await expect(frame.locator('#list-status')).toContainText('媒体库配置读取失败')
  await expect(frame.locator('#items .poster-card')).toHaveCount(0)
  expect(audit.enumerations()).toEqual([])
  await frame.locator('#new-library').click()
  await expect(frame.locator('#library-edit-status')).toContainText('媒体库配置读取失败')
  await expect(frame.locator('#library-save')).toBeDisabled()
})

test('从旧单目录设置升级不自动建库或扫描，旧观看记录保留且可重新纳入', async ({ page }) => {
  await installCinema(page, null)
  await page.goto('/apps')
  expect((await page.request.delete('/api/apps/cinema?purge_data=true')).ok()).toBe(true)
  // 合成旧清单和无扫描页面，只验证真实升级与数据兼容，不依赖旧构建产物。
  const oldPackage = await legacyCinemaPackage()
  const inspection = await page.request.post('/api/apps/inspect', { data: oldPackage, headers: { 'Content-Type': 'application/octet-stream' } })
  expect(inspection.ok()).toBe(true)
  const { digest } = await inspection.json()
  const installed = await page.request.post(`/api/apps/install?digest=${digest}`, { data: oldPackage, headers: { 'Content-Type': 'application/octet-stream' } })
  expect(installed.ok()).toBe(true)
  const old = await installed.json()
  expect((await page.request.patch('/api/apps/cinema/settings', { data: { source_dir: '/测试影视' } })).ok()).toBe(true)
  await page.goto('/apps/cinema')
  const frame = frameOf(page)
  await expect(frame.locator('body')).toHaveText('旧版影视升级夹具')
  const id = await frame.locator('body').evaluate(async () => {
    const drive = (window as any).tgdrive; await drive.ready
    const file = await drive.files.stat({ path: '/测试影视/星际旅程 S01E01.mp4' })
    await drive.storage.set(`favorite:${file.id}`, { file }, null)
    await drive.storage.set(`progress:${file.id}`, { file, seconds: 5, duration: 20, completed: false }, null)
    return file.id
  })
  await page.goto('/apps')
  const index = await (await page.request.get('/api/apps')).json()
  const available = index.available.find((item: any) => item.manifest.id === 'cinema')
  expect((await page.request.post('/api/apps/catalog/cinema/install', { data: { digest: available.digest, expected_revision: old.revision } })).ok()).toBe(true)
  const audit = cinemaRequests(page)
  await page.goto('/apps/cinema')
  await expect(frame.locator('#empty-title')).toHaveText('尚未创建媒体库')
  await expect(frame.locator('#empty')).toBeVisible()
  expect(audit.enumerations()).toEqual([])
  expect(await (await page.request.get('/api/apps/cinema/settings')).json()).toEqual({})
  await frame.locator('.sidebar [data-nav="history"]').click()
  await expect(frame.locator('#empty-title')).toHaveText('暂无媒体库内的记录')
  expect(await frame.locator('body').evaluate(async (_node, id) => !!await (window as any).tgdrive.storage.get(`progress:${id}`), id)).toBe(true)
  await frame.locator('.sidebar [data-nav="library"]').click()
  await createCinemaLibrary(page, '电影', '/测试影视')
  await frame.locator('.sidebar [data-nav="favorites"]').click()
  await expect(frame.locator('#items .poster-card')).toHaveCount(1)
  await expect(frame.getByRole('button', { name: '查看影视：星际旅程 S01E01.mp4', exact: true })).toBeVisible()
})

test('媒体库入口和编辑表单在手机及桌面保持有界布局和可用操作', async ({ page }, info) => {
  await installCinema(page, null)
  const frame = frameOf(page)
  await createCinemaLibrary(page, '电影', '/测试影视')
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: width === 1440 ? 1000 : 844 })
    await expect(frame.getByRole('button', { name: '进入媒体库：电影', exact: true })).toBeVisible()
    expect(await frame.locator('body').evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    await frame.getByRole('button', { name: '编辑媒体库：电影', exact: true }).click()
    await expect(frame.locator('#library-name')).toHaveValue('电影')
    expect(await frame.locator('#library-edit-dialog').evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    await expect(frame.locator('#library-save')).toBeVisible()
    await page.screenshot({ path: info.outputPath(`cinema-library-editor-${width}.png`), fullPage: true })
    await frame.locator('#library-cancel').click()
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await frame.locator('#mobile-source').click()
  await expect(frame.locator('#libraries .library-card')).toHaveCount(1)
  await enterCinemaLibrary(page, '电影')
  await frame.locator('#library-back').click()
  await expect(frame.locator('#libraries .library-card')).toHaveCount(1)
})
