import { expect, test } from '@playwright/test'
import { seedReaderSource } from './reader-helpers'

for (const width of [390, 1280]) test(`宿主全库子目录分页、重开恢复、文件变更拒绝旧游标（${width}）`, async ({ page }) => {
  await page.setViewportSize({ width, height: 844 })
  expect(await (await page.request.get('/__apps_fixture')).json()).toEqual({ fixture: 'tgdrive-apps-tests' })
  expect((await page.request.post('/api/auth/login', { data: { username: 'apps-test', password: 'apps-test-only' } })).ok()).toBe(true)
  const apps = await (await page.request.get('/api/apps')).json()
  for (const app of apps.installed) expect((await page.request.delete(`/api/apps/${app.manifest.id}?purge_data=true`)).ok()).toBe(true)
  const available = apps.available.find((app: any) => app.manifest.id === 'books')
  expect((await page.request.post('/api/apps/catalog/books/install', { data: { digest: available.digest } })).ok()).toBe(true)
  await seedReaderSource(page, 'books', '/全库分页')
  expect((await page.request.patch('/api/apps/books/scope', { data: { mode: 'selected', paths: ['/全库分页'] } })).ok()).toBe(true)
  await page.goto('/apps/books')
  const frame = page.frameLocator('iframe')
  await frame.locator('#btn-home-view-all').click()
  await frame.locator('#btn-view-host').click()
  await expect(frame.locator('#host-items .library-card')).toHaveCount(40)
  await expect(frame.locator('#host-items')).toContainText('书000.txt')
  await frame.locator('#host-next').click()
  await expect(frame.locator('#host-items')).toContainText('书040.txt')
  await expect(frame.locator('#host-page')).toHaveText('第 2 页')
  await expect.poll(() => frame.locator('body').evaluate(async () => (await window.tgdrive.storage.get<any>('library:host-position:v1'))?.value.page)).toBe(2)
  await page.reload()
  await frame.locator('#btn-home-view-all').click()
  await frame.locator('#btn-view-host').click()
  await expect(frame.locator('#host-page')).toHaveText('第 2 页')
  await expect(frame.locator('#host-items')).toContainText('书040.txt')
  await frame.locator('#host-next').click()
  await expect(frame.locator('#host-items .library-card')).toHaveCount(5)
  await expect(frame.locator('#host-next')).toBeDisabled()
  const query = await frame.locator('body').evaluate(async () => (await window.tgdrive.storage.get<any>('library:host-position:v1'))?.value.query)
  expect((await page.request.post('/api/fs/mkdir', { data: { path: `/全库分页/修订${width}` } })).ok()).toBe(true)
  const error = await frame.locator('body').evaluate(async (_node, query) => {
    try { await window.tgdrive.library!.page(query); return null } catch (error) { return (error as any).code }
  }, query)
  expect(error).toBe('reading_index_changed')
  await frame.locator('#host-refresh').click()
  await expect(frame.locator('#host-items .library-card')).toHaveCount(40)
  await frame.locator('#host-search').fill('书084')
  await frame.locator('#host-apply').click()
  await expect(frame.locator('#host-items .library-card')).toHaveCount(1)
  await expect(frame.locator('#host-items')).toContainText('书084.txt')
  expect(await frame.locator('body').evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await frame.locator('#host-items .library-card').click()
  await expect(frame.locator('#reader')).toBeVisible()
})
